instance_type: "ml.g5.xlarge"
instance_count: 1
volume_size_gb: 50
max_runtime_seconds: 7200

s3_data_uri: "s3://fine-tune-automotive-data/data/automotive_en_dataset.jsonl"
s3_output_uri: "s3://fine-tune-automotive-data/output/"

job_name_prefix: "car-maintain-qlora"
pytorch_version: "2.8.0"
python_version: "py312"
transformers_version: "4.56.2"
